/**
 * Copyright (C) 2010 Sopra Steria Group (movalys.support@soprasteria.com)
 *
 * This file is part of Movalys MDK.
 * Movalys MDK is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Movalys MDK is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License
 * along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.
 */
package com.a2a.adjava.languages.ios.xmodele;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * IOS ExpandableList Xib components description
 * @author qlagarde
 *
 */

@XmlRootElement(name="xib-container")
@XmlAccessorType(XmlAccessType.FIELD)
public class MIOSExpandableListXibContainer extends MIOSXibContainer{
	
	/**
	 * Does nothing
	 */
	public MIOSExpandableListXibContainer() {
		// nothing to do
	}
	
	/**
	 * Name of the view of the section of multi list
	 */
	@XmlElement(name="view-expandablelist-section-name")
	private String viewExpandableListSectionName = null ;
	
	/**
	 * Name of the view of the header opf the multi list
	 */
	@XmlElement(name="view-expandablelist-header-name")
	private String viewExpandableListHeaderName = null ;
	
	/**
	 * Constructor
	 * @param p_sComputeXibNameOfExpandableListSection the name to use for the instance
	 */
	public MIOSExpandableListXibContainer(String p_sComputeXibNameOfExpandableListSection) {
		super(p_sComputeXibNameOfExpandableListSection);
	}

	/**
	 * Returns the name of the class that manages the view of the section generated by this XIB container
	 * @return the name of the class that manages the view of the section generated by this XIB container
	 */
	public String getViewExpandableListSectionName() {
		return viewExpandableListSectionName;
	}

	/**
	 * Sets the name of the class that manages the view of the section generated by this XIB container
	 * @param p_sViewExpandableListSectionName The name of the class that manages the view of the section generated by this XIB container
	 */
	public void setViewExpandableListSectionName(String p_sViewExpandableListSectionName) {
		this.viewExpandableListSectionName = p_sViewExpandableListSectionName;
	}

	/**
	 * Returns the name of the class that manages the view of the header generated by this XIB container
	 * @return the name of the class that manages the view of the header generated by this XIB container
	 */
	public String getViewExpandableListHeaderName() {
		return viewExpandableListHeaderName;
	}

	/**
	 * Sets the name of the class that manages the view of the header generated by this XIB container
	 * @param p_sViewExpandableListHeaderName The name of the class that manages the view of the header generated by this XIB container
	 */
	public void setViewExpandableListHeaderName(String p_sViewExpandableListHeaderName) {
		this.viewExpandableListHeaderName = p_sViewExpandableListHeaderName;
	}

		
}
